//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment_log
    {
        public int ID { get; set; }
        public Nullable<int> Account_Number { get; set; }
        public Nullable<byte> Initial_Assessment { get; set; }
        public Nullable<byte> Update_Assessment { get; set; }
        public Nullable<byte> Update_PCU { get; set; }
        public Nullable<byte> OneTime_PA { get; set; }
        public Nullable<byte> Initial_PA_Process { get; set; }
        public Nullable<byte> POS_RWO_Created { get; set; }
        public Nullable<byte> Faxes_to_State { get; set; }
        public Nullable<byte> LM_Letter { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string User_ID { get; set; }
    }
}
