//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCN_Claims_FTP
    {
        public int Id { get; set; }
        public Nullable<double> Contract { get; set; }
        public Nullable<double> PlanGroup { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_int { get; set; }
        public Nullable<double> Mbr_suffix { get; set; }
        public string Claim_id { get; set; }
        public Nullable<double> Clm_suffix { get; set; }
        public string Claim_Payee { get; set; }
        public string Serv_Prov { get; set; }
        public string Serv_Prov_Name { get; set; }
        public string Bcat { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<System.DateTime> Paid_Date { get; set; }
        public Nullable<System.DateTime> Submit_Date { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<double> Copay { get; set; }
        public Nullable<double> COB { get; set; }
        public Nullable<double> Allowed { get; set; }
        public Nullable<double> Deductible { get; set; }
        public Nullable<double> Coinsurance { get; set; }
        public string Proc_Code { get; set; }
        public Nullable<double> Units { get; set; }
        public string EX_code { get; set; }
        public string EX_description { get; set; }
        public Nullable<double> Charge_Amt { get; set; }
        public Nullable<double> Serv_Prov_NPI { get; set; }
        public Nullable<double> Payee_Prov_NPI { get; set; }
        public Nullable<System.DateTime> Mbr_DOB { get; set; }
        public string Mod1 { get; set; }
        public string Mod2 { get; set; }
        public string Mod3 { get; set; }
        public string Mod4 { get; set; }
        public string On_Off_exchange { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
    }
}
