//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMPS_Error_Codes
    {
        public string errCode { get; set; }
        public string errShortDesc { get; set; }
        public string errRemitCode { get; set; }
        public string errAdjCode { get; set; }
        public Nullable<byte> errHighlight { get; set; }
    }
}
