//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMPS_Ignore_Errors
    {
        public int cieID { get; set; }
        public string cieCode { get; set; }
        public Nullable<System.DateTime> cieAdded { get; set; }
        public string cieAddedBy { get; set; }
        public Nullable<System.DateTime> cieDeleted { get; set; }
        public string cieDeletedBy { get; set; }
    }
}
