//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimsToSubmit_Fixed
    {
        public int csfID { get; set; }
        public Nullable<int> csfClaim { get; set; }
        public string csfUBReason { get; set; }
        public Nullable<System.DateTime> csfUBFixed { get; set; }
        public string csfUBFixedBy { get; set; }
    }
}
