//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eligibility_Orders
    {
        public int ordID { get; set; }
        public Nullable<int> ordELRid { get; set; }
        public Nullable<int> ordWOId { get; set; }
        public Nullable<System.DateTime> ordAdded { get; set; }
    }
}
