//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eligibility_EOD_Process
    {
        public int eodID { get; set; }
        public Nullable<System.DateTime> eodDate { get; set; }
        public Nullable<System.DateTime> eodClosed { get; set; }
        public string eodClosedBy { get; set; }
        public Nullable<System.DateTime> eodDeleted { get; set; }
        public string eodDeletedBy { get; set; }
    }
}
