//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_New
    {
        public int empID { get; set; }
        public string empLogin { get; set; }
        public string empEmail { get; set; }
        public string empFullName { get; set; }
        public Nullable<byte> empManager { get; set; }
        public Nullable<byte> empTeamLeader { get; set; }
        public Nullable<byte> empCanEnterTicket { get; set; }
        public Nullable<int> empDepartment { get; set; }
        public Nullable<int> empTeam { get; set; }
        public Nullable<System.DateTime> empAdded { get; set; }
        public Nullable<System.DateTime> empRemoved { get; set; }
        public Nullable<System.DateTime> empAutoUpdate { get; set; }
        public Nullable<byte> empSort { get; set; }
        public string empPhone { get; set; }
        public Nullable<double> empPOSid { get; set; }
    }
}
