//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_OrderLines
    {
        public int linID { get; set; }
        public Nullable<int> linWOid { get; set; }
        public string linProductCode { get; set; }
        public Nullable<int> linQty { get; set; }
        public Nullable<byte> linQtyAvailable { get; set; }
        public Nullable<byte> linIssue { get; set; }
    }
}
