//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpiredProduct
    {
        public int ID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<short> Qty { get; set; }
        public Nullable<int> ID_UOM { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public string CountedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateRemoved { get; set; }
        public string RemovedBy { get; set; }
        public Nullable<int> ID_Product { get; set; }
    }
}
