//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FedExLogins
    {
        public int felID { get; set; }
        public string felName { get; set; }
        public string felUser { get; set; }
        public string felPass { get; set; }
        public Nullable<System.DateTime> felUpdated { get; set; }
        public string felUpdatedBy { get; set; }
        public Nullable<System.DateTime> felDeleted { get; set; }
        public string felDeletedBy { get; set; }
        public Nullable<System.DateTime> felAdded { get; set; }
        public string felAddedBy { get; set; }
    }
}
