//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndianaMedicaidSurvey
    {
        public int imsID { get; set; }
        public string imsQ1 { get; set; }
        public string imsQ2 { get; set; }
        public string imsQ3 { get; set; }
        public string imsQ4 { get; set; }
        public string imsQ5 { get; set; }
        public string imsQ6 { get; set; }
        public string imsName { get; set; }
        public string imsAddress { get; set; }
        public string imsComment { get; set; }
        public Nullable<System.DateTime> imsEnteredDate { get; set; }
        public string imsEnteredBy { get; set; }
    }
}
