//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class JBCCServiceTypes
    {
        public int Id { get; set; }
        public string ServiceType { get; set; }
        public Nullable<System.DateTime> SelectedOn { get; set; }
        public Nullable<int> SelectedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool DeletedBy { get; set; }
    }
}
