//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class JBCCServicePayers
    {
        public int Id { get; set; }
        public int PayerID { get; set; }
        public int PayerTypeID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public bool ShouldAutoRelease { get; set; }
        public Nullable<System.DateTime> SelectedOn { get; set; }
        public Nullable<int> SelectedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public int DeletedBy { get; set; }
    }
}
