//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntranetEntitiesTest : DbContext
    {
        public IntranetEntitiesTest()
            : base("name=IntranetEntitiesTest")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees_New> Employees_New { get; set; }
        public virtual DbSet<CHAMPS_Adj_Codes> CHAMPS_Adj_Codes { get; set; }
        public virtual DbSet<CHAMPS_Error_Codes> CHAMPS_Error_Codes { get; set; }
        public virtual DbSet<CHAMPS_Remit_Codes> CHAMPS_Remit_Codes { get; set; }
        public virtual DbSet<CHAMPS_Ignore_Errors> CHAMPS_Ignore_Errors { get; set; }
    }
}
