//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityOnHand
    {
        public int ID { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> QtyOnHand { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
