//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account_Note_History
    {
        public int ID { get; set; }
        public Nullable<int> ID_Note { get; set; }
        public Nullable<System.DateTime> NoteDate { get; set; }
        public string NoteText { get; set; }
        public Nullable<int> ID_Operator { get; set; }
        public Nullable<int> Tag { get; set; }
        public Nullable<int> PSR_ID { get; set; }
        public string ExternalReference { get; set; }
    }
}
