//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inv_Vendor_Table
    {
        public int ID { get; set; }
        public string VendorName { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone_Number { get; set; }
        public string Fax_Number { get; set; }
        public string Email { get; set; }
        public string Internet { get; set; }
        public string Contact { get; set; }
        public string Comments { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<int> ID_Payment_Terms { get; set; }
        public string Service_Phone_Number { get; set; }
        public string Service_Fax_Number { get; set; }
        public string EDISenderID { get; set; }
        public string EDIReceiverID { get; set; }
        public string EDILogin { get; set; }
        public string EDIPassword { get; set; }
        public string EDIURL { get; set; }
        public Nullable<int> ID_DeliveryMethod { get; set; }
        public Nullable<int> ID_OperatorForOrders { get; set; }
        public Nullable<int> X12TransmitControl { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<int> ID_ChangedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ID_DeletedBy { get; set; }
        public Nullable<short> LeadTimeDays { get; set; }
        public Nullable<int> ID_VendorGroup { get; set; }
        public Nullable<int> PN_DeliveryLocation { get; set; }
        public Nullable<int> PN_Ranking { get; set; }
        public string ExternalReference { get; set; }
        public string BillToName { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToCity { get; set; }
        public string BillToState { get; set; }
        public string BillToZip { get; set; }
        public string BillToPhone { get; set; }
        public string BillToFax { get; set; }
        public string BillToContact { get; set; }
        public string ContactTitle { get; set; }
        public string ContactEmail { get; set; }
        public string BillToContactTitle { get; set; }
        public string BillToContactEmail { get; set; }
        public Nullable<short> PN_EnableInventoryTracking { get; set; }
        public Nullable<double> PN_VariableCostPercent { get; set; }
        public Nullable<int> PN_ID_VariableCostAllowable { get; set; }
        public string EDIElementSeparator { get; set; }
        public string EDISubElementSeparator { get; set; }
        public string EDISegmentTerminator { get; set; }
        public Nullable<short> PN_VariableCostCodeToUse { get; set; }
        public string EDIDropShipCutOffTime { get; set; }
        public Nullable<short> EDICreateConfirmationImage { get; set; }
        public string GL_AP_ShippingCost { get; set; }
        public Nullable<short> EDITestMode { get; set; }
        public Nullable<decimal> DefaultUnitShippingCost { get; set; }
        public string EDIISA07 { get; set; }
        public string EDIPO106 { get; set; }
        public Nullable<short> EDIDontSendEmail { get; set; }
        public Nullable<short> EDI810Confirmation { get; set; }
        public string EDIBEG02_Stock { get; set; }
        public string EDIBEG02_DropShip { get; set; }
        public Nullable<short> EDIBEG_PER { get; set; }
    }
}
