//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MassCancel_History
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string ActionBy { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string CancelNote { get; set; }
    }
}
