//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product_Table
    {
        public int ID { get; set; }
        public string ProductCode { get; set; }
        public string ProductDescription { get; set; }
        public string RecType { get; set; }
        public string MfgPart { get; set; }
        public Nullable<int> ID_Manufacturer { get; set; }
        public Nullable<int> ID_BillingCode { get; set; }
        public Nullable<int> ID_ProductCategory { get; set; }
        public string BillingCodeMacro { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public Nullable<int> ID_UOM { get; set; }
        public Nullable<short> PerUnitQty { get; set; }
        public Nullable<bool> SerializedItem { get; set; }
        public Nullable<short> HowToOrder { get; set; }
        public Nullable<short> AnalysisRating { get; set; }
        public Nullable<short> DepreciationMonths { get; set; }
        public string NDC { get; set; }
        public string UniversalProductNumberQualifier { get; set; }
        public string UniversalProductNumber { get; set; }
        public Nullable<decimal> DefaultSalvageValue { get; set; }
        public Nullable<short> ComplianceCreateOption { get; set; }
        public Nullable<int> ComplianceDocumentTypeID { get; set; }
        public Nullable<short> ReoccurringCreateOption { get; set; }
        public string ReoccurringFreq { get; set; }
        public string Comments { get; set; }
        public Nullable<short> JCAHOMaintInterval { get; set; }
        public Nullable<short> JCAHOClinicalInterval { get; set; }
        public Nullable<short> PrintBarcodes { get; set; }
        public Nullable<short> Availability { get; set; }
        public Nullable<double> UnitWeight { get; set; }
        public Nullable<bool> MayExpire { get; set; }
        public Nullable<bool> SuppressIfInMacro { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ID_ChangedBy { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ID_DeletedBy { get; set; }
        public Nullable<int> ID_MaintPM { get; set; }
        public Nullable<short> SearchDisplayColor { get; set; }
        public string D_MS_PNID { get; set; }
        public string D_PkgDrugName { get; set; }
        public string D_GenericName { get; set; }
        public string D_Strength { get; set; }
        public string D_StrengthUOM { get; set; }
        public string D_PkgDescCode { get; set; }
        public Nullable<short> D_PkgQty { get; set; }
        public Nullable<double> D_PkgSize { get; set; }
        public string D_DoseForm { get; set; }
        public string D_DoseFormAbbrev { get; set; }
        public string D_DoseUnits { get; set; }
        public Nullable<int> D_ID_Storage { get; set; }
        public Nullable<decimal> D_AWPUnitPrice { get; set; }
        public Nullable<decimal> D_AWPPerPkg { get; set; }
        public string D_MfgName { get; set; }
        public Nullable<int> D_MS_DNID { get; set; }
        public Nullable<int> D_MS_DDID { get; set; }
        public Nullable<System.DateTime> D_LastMedispanValidation { get; set; }
        public Nullable<short> D_CompoundStableDays { get; set; }
        public string UPC1 { get; set; }
        public string UPC2 { get; set; }
        public string UPC3 { get; set; }
        public string D_UnitOfMeasure { get; set; }
        public Nullable<short> D_DefaultRxLength { get; set; }
        public Nullable<short> D_IsControlledSubstance { get; set; }
        public string D_WarningMessage { get; set; }
        public Nullable<short> D_RequireRxQtyLimit { get; set; }
        public string D_LabelDescription { get; set; }
        public Nullable<int> D_ID_CompoundProfile { get; set; }
        public string D_SubmitHCPC { get; set; }
        public Nullable<decimal> D_ASPUnitPrice { get; set; }
        public Nullable<int> ID_CreatedBy { get; set; }
        public string D_Reconstitute_Instructions { get; set; }
        public string D_GPI { get; set; }
        public Nullable<short> ServiceableItem { get; set; }
        public Nullable<short> ComplianceExport { get; set; }
        public Nullable<short> D_SeperateLineForEachTherapyDay { get; set; }
        public Nullable<double> D_DiluentAmount { get; set; }
        public Nullable<short> D_NoMonographs { get; set; }
        public string ProductDetailDescription { get; set; }
        public Nullable<short> D_TPN_Type { get; set; }
        public Nullable<short> D_SolutionType { get; set; }
        public Nullable<short> D_SoldAsCompletePkg { get; set; }
        public Nullable<System.DateTime> D_MedispanInactiveDate { get; set; }
        public string D_DEAClassCode { get; set; }
        public Nullable<short> D_Bypass_rPH_FinalApproval { get; set; }
        public string D_NDCFormatCode { get; set; }
        public Nullable<decimal> D_WAC_UnitPrice { get; set; }
        public Nullable<short> RequireLotNumber { get; set; }
        public Nullable<double> D_mEqPerML { get; set; }
        public Nullable<System.DateTime> D_EarlyReleaseDrugCreated { get; set; }
        public Nullable<System.DateTime> D_EarlyReleaseDrugVerified { get; set; }
        public Nullable<short> CustomItem { get; set; }
        public Nullable<short> EstSetupTimeMinutes { get; set; }
        public string D_DescDisplay { get; set; }
        public Nullable<double> D_mMolPerML { get; set; }
        public Nullable<double> D_mgPerML { get; set; }
        public Nullable<short> NonbillableItem { get; set; }
        public Nullable<short> RecStatusIndicator { get; set; }
        public Nullable<short> D_CompoundStableDaysFrozen { get; set; }
        public Nullable<short> D_CompoundStableDaysRefrigerated { get; set; }
        public Nullable<short> D_ExcludeFromCompounder { get; set; }
        public Nullable<short> D_ExcludeFromDIcheck { get; set; }
        public string D_WarningLabel_1 { get; set; }
        public string D_WarningLabel_2 { get; set; }
        public string D_WarningLabel_3 { get; set; }
        public string D_WarningLabel_4 { get; set; }
        public string D_WarningLabel_5 { get; set; }
        public string D_WarningLabel_6 { get; set; }
        public string D_DrugImprint { get; set; }
        public Nullable<System.DateTime> AcceptableExceptionDate { get; set; }
        public Nullable<int> ID_AcceptableExceptionBy { get; set; }
        public Nullable<double> D_DiluentPwdrVol { get; set; }
        public Nullable<short> D_DiluentInDoseVol { get; set; }
        public string D_MS_DrugName { get; set; }
        public Nullable<short> D_BillQtyIndicator { get; set; }
        public Nullable<double> D_DispenseSizeOverride { get; set; }
        public string D_DispenseUOMOverride { get; set; }
    }
}
