//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account_Insurance
    {
        public int Account { get; set; }
        public short Entry_Number { get; set; }
        public int ID_Payer { get; set; }
        public Nullable<int> ID_Plan { get; set; }
        public Nullable<short> SubscriberMember { get; set; }
        public Nullable<short> SubscriberRelationship { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public Nullable<System.DateTime> LastVerified_Date { get; set; }
        public string Service_Code { get; set; }
        public string Check_Digit { get; set; }
        public string Control { get; set; }
        public string Plan_Code { get; set; }
        public string Reciprocity { get; set; }
        public string GroupCode { get; set; }
        public string Contract { get; set; }
        public Nullable<short> IsMasterMedical { get; set; }
        public string Policy_Number { get; set; }
        public string Enrollment { get; set; }
        public string Sponsor { get; set; }
        public string Branch { get; set; }
        public string Pay_Grade { get; set; }
        public string Status { get; set; }
        public string Other_Insurance_Code { get; set; }
        public string Level_Of_Care { get; set; }
        public string Case_Number { get; set; }
        public string BenefitCode { get; set; }
        public string Comments { get; set; }
        public Nullable<double> CoveragePercent { get; set; }
        public Nullable<short> CoverageMet { get; set; }
        public Nullable<decimal> DeductibleAmount { get; set; }
        public Nullable<short> DeductibleMet { get; set; }
        public Nullable<decimal> OutOfPocketAmount { get; set; }
        public Nullable<short> OutOfPocketMet { get; set; }
        public Nullable<decimal> CarveOutPolicyAmount { get; set; }
        public Nullable<short> CarveOutPolicyMet { get; set; }
        public Nullable<short> PaymentsMadeToPatient { get; set; }
        public Nullable<short> InsurancePaysIfPrimaryDenies { get; set; }
        public Nullable<short> RejectionIsNeeded { get; set; }
        public Nullable<short> EquipCapToPurchasePrice { get; set; }
        public Nullable<short> IsMCRSupplement { get; set; }
        public Nullable<short> MCRSUP_DeductCopay { get; set; }
        public Nullable<short> MCRSUP_CopayOnly { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public Nullable<int> Last_Updated_User { get; set; }
        public Nullable<short> SuppressFromLedger { get; set; }
        public Nullable<int> ID_ManagedCareHealthPlan { get; set; }
        public Nullable<int> ID_ManagedCareMedicalGroup { get; set; }
        public string LastVerified_Details { get; set; }
        public Nullable<System.DateTime> LastRealTimeVerified_DateTime { get; set; }
        public Nullable<System.DateTime> LastVerifiedReceived_DateTime { get; set; }
        public Nullable<System.DateTime> CardIssuedDate { get; set; }
        public Nullable<short> MCR_InsTypeCode { get; set; }
        public string ExternalReference { get; set; }
        public Nullable<short> EPSDT { get; set; }
        public Nullable<short> CoverageBypass { get; set; }
        public string Insurer_OnFile_FirstName { get; set; }
        public string Insurer_OnFile_Middle { get; set; }
        public string Insurer_OnFile_LastName { get; set; }
        public Nullable<System.DateTime> Insurer_OnFile_BirthDate { get; set; }
        public string Insurer_OnFile_Address_1 { get; set; }
        public string Insurer_OnFile_Address_2 { get; set; }
        public string Insurer_OnFile_City { get; set; }
        public string Insurer_OnFile_State { get; set; }
        public string Insurer_OnFile_Zip { get; set; }
        public Nullable<short> Pricing340B { get; set; }
        public Nullable<short> NCPDP_PersonCodeOverride { get; set; }
        public string Legacy_PolicyNumber { get; set; }
        public Nullable<System.DateTime> Legacy_PolicyNumber_ChangeDate { get; set; }
        public string ProcessorControlNumberOverride { get; set; }
    }
}
