//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CSRCallLog
    {
        public int id { get; set; }
        public string RefNum { get; set; }
        public Nullable<int> Account { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string CallDuration { get; set; }
        public string Name { get; set; }
        public string Relation { get; set; }
        public string OtherRelName { get; set; }
        public string BillingTxt { get; set; }
        public string DocumentationTxt { get; set; }
        public string DemographicChangesTxt { get; set; }
        public string TypeSupplies_1 { get; set; }
        public string TypeSupplies_2 { get; set; }
        public string TypeSuppliesOther { get; set; }
        public string ShippingOthersName { get; set; }
        public string InsuranceChangeTxt { get; set; }
        public string NewAccountTxt { get; set; }
        public string OrderConfirmationTxt { get; set; }
        public string OrderStatusTxt { get; set; }
        public string RWOChangeTxt { get; set; }
        public string SampleTxt { get; set; }
        public string ShippingIssueTxt { get; set; }
        public string TransferredCall { get; set; }
        public string TransferredCallTxt { get; set; }
        public string OtherHandlingTxt { get; set; }
        public bool VerifiedPHI { get; set; }
        public bool VoiceForHealth { get; set; }
        public bool Eligibility { get; set; }
        public bool Copay { get; set; }
        public bool Billing { get; set; }
        public bool Address { get; set; }
        public bool Physician { get; set; }
        public bool Phone { get; set; }
        public bool AOB { get; set; }
        public bool Prescription { get; set; }
        public bool CMN { get; set; }
        public bool PriorAuthorization { get; set; }
        public bool SupportingDoc { get; set; }
        public bool TeacherLetter { get; set; }
        public bool ABN { get; set; }
        public bool Logs { get; set; }
        public bool InsuarnceChanges_ { get; set; }
        public bool NewAcconunt { get; set; }
        public bool Restart { get; set; }
        public bool OrderConfirmation { get; set; }
        public bool FedExOrUSPSTracking { get; set; }
        public bool OrderShipped { get; set; }
        public bool OrderETA { get; set; }
        public bool OrderHolding { get; set; }
        public bool RWOCreated { get; set; }
        public bool PC_IncreaseOrDecrease { get; set; }
        public bool PC_Hold { get; set; }
        public bool PC_RemoveOrAdd { get; set; }
        public bool ProductChange { get; set; }
        public bool DefectiveProductOrNotUsable { get; set; }
        public bool WrongOrExtraProductShipped { get; set; }
        public bool MissingProduct { get; set; }
        public bool ShippingOther { get; set; }
        public bool ReturnedCall_LeftVoicemail { get; set; }
        public bool WrongNumber { get; set; }
        public bool Nursing_CSRassessment { get; set; }
        public bool AccountDeactivate { get; set; }
        public string ComplaintOutcome { get; set; }
        public string TrackingNumber { get; set; }
        public string WorkOrder { get; set; }
        public bool Damaged { get; set; }
        public bool Driver { get; set; }
        public bool WrongProductShipped { get; set; }
        public bool QualityOfProdut { get; set; }
        public bool WrongArea { get; set; }
        public bool OtherIssue_MissingProduct { get; set; }
        public string FedExTxt { get; set; }
        public bool ProductIncrease { get; set; }
        public bool ProductMispick { get; set; }
        public bool ProductDefective { get; set; }
        public string ProductTxt { get; set; }
        public bool ImpoliteORoffensive { get; set; }
        public bool HoldTimes { get; set; }
        public string customerServiceTxt { get; set; }
        public string OtherTxt { get; set; }
        public string FedExOrUSPSTrackingNumber { get; set; }
        public bool SampleChoice { get; set; }
        public bool SampleTask { get; set; }
        public bool Other_CallHandling { get; set; }
        public bool LMN { get; set; }
        public bool Call { get; set; }
        public bool Task { get; set; }
        public bool Web { get; set; }
        public bool Fax { get; set; }
        public bool Email { get; set; }
        public bool LogTypeOther { get; set; }
        public string Product { get; set; }
        public string DeliveryCompany { get; set; }
        public string BCNProvider { get; set; }
        public bool Other { get; set; }
        public bool BCNProviderIssue { get; set; }
        public bool InsLimitGuidelines { get; set; }
        public bool PhysicianIssue { get; set; }
        public bool NeverRecivedSupplies { get; set; }
        public bool NoFollowUpWithMem { get; set; }
        public bool ReturnedFromVM { get; set; }
        public bool NoFollowUp { get; set; }
        public bool Website { get; set; }
        public bool VirtualCallBack { get; set; }
        public bool SAJamesSelfService { get; set; }
        public bool SAJamesPhonePromts { get; set; }
        public bool VPaymentCalles { get; set; }
        public bool VConfirmationCalls { get; set; }
        public bool DidntFollowDelIns { get; set; }
        public bool CivilRight { get; set; }
        public bool Compliance { get; set; }
        public bool CustomerService { get; set; }
        public bool Discrimination { get; set; }
        public bool HealthPlan { get; set; }
        public bool ProductDefectiveQuality { get; set; }
        public bool ShippingUSPS { get; set; }
        public bool ShippingWarehouse { get; set; }
        public bool SmartAction { get; set; }
        public bool TextMessaging { get; set; }
        public bool WebsitePortal { get; set; }
        public bool BloodPressureMonitors { get; set; }
        public bool BreastPumps { get; set; }
        public bool ContGlucoseMonitoring { get; set; }
        public bool DiabeticTestSup { get; set; }
        public bool EnteralNutrition { get; set; }
        public bool ExternalDefibrillator { get; set; }
        public bool IncontinenceSupplies { get; set; }
        public bool InsulinPumpsSupplies { get; set; }
        public bool InsSyrPenNeed { get; set; }
        public bool OstomySupplies { get; set; }
        public bool PleurXDrainSys { get; set; }
        public bool PTINRTesting { get; set; }
        public bool TENSUnitSup { get; set; }
        public bool UrologicalSupplies { get; set; }
        public bool WoundCareSupplies { get; set; }
        public bool OtherUnsureSupplies { get; set; }
        public bool BDI { get; set; }
        public bool BPnBPM { get; set; }
        public bool CallCenter { get; set; }
        public bool CSRAssessment { get; set; }
        public bool DynamicSynergy { get; set; }
        public bool Enteral { get; set; }
        public bool HGS { get; set; }
        public bool InsulinPumpCGM { get; set; }
        public bool MedicalDocuments { get; set; }
        public bool NewAccountTeam { get; set; }
        public bool Nurses { get; set; }
        public bool QualityAssurance { get; set; }
        public bool Shipping { get; set; }
        public bool THC { get; set; }
        public bool Troy { get; set; }
        public bool Verification { get; set; }
        public bool WebSupport { get; set; }
        public bool WoundCareOstomyTENS { get; set; }
        public bool OtherUnsureTeam { get; set; }
    }
}
