//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MedDoc_Type_Table
    {
        public int ID { get; set; }
        public string DocTypeDescription { get; set; }
        public Nullable<short> CMNReplyQuestionFormat { get; set; }
        public bool CMNNeedsEquipCosts { get; set; }
        public bool SystemType { get; set; }
        public string DefaultHCPC1 { get; set; }
        public string DefaultHCPC2 { get; set; }
        public string DefaultHCPC3 { get; set; }
        public string DefaultHCPC4 { get; set; }
        public Nullable<short> RecertForSalesItems { get; set; }
        public string ExternalReference { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<int> ID_ChangedBy { get; set; }
        public Nullable<short> PharmacyRxType { get; set; }
        public Nullable<short> SuppressSignatureSection { get; set; }
        public Nullable<short> StateRegulationRxRenewal { get; set; }
        public Nullable<short> ComplexItemsType { get; set; }
        public Nullable<short> PharmacyRxTPNType { get; set; }
        public Nullable<short> PhysicianOrderType { get; set; }
        public Nullable<short> PharmacyRxCompoundType { get; set; }
        public Nullable<short> NursingDocumentType { get; set; }
        public string DefaultHCPC5 { get; set; }
        public string DefaultHCPC6 { get; set; }
        public string DefaultHCPC7 { get; set; }
        public string DefaultHCPC8 { get; set; }
        public string DefaultHCPC9 { get; set; }
        public string DefaultHCPC10 { get; set; }
        public string DefaultHCPC11 { get; set; }
        public string DefaultHCPC12 { get; set; }
        public Nullable<short> PharmacyRxFactorType { get; set; }
        public Nullable<short> PharmacyRxTrackByDoses { get; set; }
        public Nullable<short> PharmacyRxLabelSize { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ID_CreatedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ID_DeletedBy { get; set; }
    }
}
