//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PS_RepeatingOrders
    {
        public int ID { get; set; }
        public int Account { get; set; }
        public Nullable<short> Member { get; set; }
        public Nullable<System.DateTime> NextRepeatDate { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public string ItemLineComment { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> WorkOrderType { get; set; }
        public Nullable<short> AcceptAssignment { get; set; }
        public Nullable<int> ID_DeliveryLocation { get; set; }
        public Nullable<int> ID_DeliveryMethod { get; set; }
        public Nullable<int> ID_DeliveryTime { get; set; }
        public Nullable<int> ID_CMN { get; set; }
        public Nullable<int> ID_PA { get; set; }
        public string LineNarrative { get; set; }
        public Nullable<short> Hold { get; set; }
        public Nullable<int> ID_CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ID_Changed { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<short> ReleasedByOutReachInterface { get; set; }
        public Nullable<short> CBAValidationInteraction { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ID_DiscountPlan { get; set; }
        public Nullable<int> ID_HealthcallCarePlans { get; set; }
        public Nullable<short> MakeIncompleteWO { get; set; }
        public Nullable<int> ID_OriginatedWOLine { get; set; }
        public Nullable<int> ID_Incident { get; set; }
        public Nullable<int> ID_PA2 { get; set; }
        public Nullable<int> Tag { get; set; }
    }
}
