//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductCategory_Table
    {
        public int ID { get; set; }
        public string CategoryDescription { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ID_DeletedBy { get; set; }
        public Nullable<int> ID_PreferredProvider { get; set; }
        public Nullable<short> UseSalesTaxRate2 { get; set; }
        public Nullable<short> StateTaxOnly { get; set; }
        public string GL_GrossSales { get; set; }
        public string GL_ContractualAdj { get; set; }
        public string GL_Expected { get; set; }
        public string GL_COGS { get; set; }
        public string GL_COGSCredit { get; set; }
        public string GL_COGSCreditLease { get; set; }
        public string GL_ADJ_Group1 { get; set; }
        public string GL_ADJ_Group2 { get; set; }
        public string GL_ADJ_Group3 { get; set; }
        public string GL_ADJ_Group4 { get; set; }
        public string GL_ADJ_Group5 { get; set; }
        public string GL_ADJ_Credit { get; set; }
        public string GL_AP { get; set; }
        public string GL_Depreciation { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<int> ID_ChangedBy { get; set; }
        public string GL_AR { get; set; }
        public string GL_Cash { get; set; }
        public string GL_Inventory { get; set; }
        public Nullable<short> PatientOutreach { get; set; }
        public string OutreachCategoryReferenceCode { get; set; }
        public string GL_Refunds { get; set; }
    }
}
