//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account_Member
    {
        public int Account { get; set; }
        public short Member { get; set; }
        public string Indicator { get; set; }
        public string First_Name { get; set; }
        public string Middle { get; set; }
        public string Last_Name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> Deceased { get; set; }
        public string Marital_Status { get; set; }
        public string Social_Security { get; set; }
        public string Dx1 { get; set; }
        public string DxCause1 { get; set; }
        public string Dx2 { get; set; }
        public string DxCause2 { get; set; }
        public string Dx3 { get; set; }
        public string DxCause3 { get; set; }
        public string Dx4 { get; set; }
        public string DxCause4 { get; set; }
        public string Allergies { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string AltPhone { get; set; }
        public string County { get; set; }
        public string EmailAddress { get; set; }
        public string ShipToAddress_1 { get; set; }
        public string ShipToAddress_2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToZip { get; set; }
        public string ShipToPhone { get; set; }
        public string ShipToAltPhone { get; set; }
        public Nullable<int> ID_Default_Referring_Doctor { get; set; }
        public Nullable<System.DateTime> DatePCPVerifiedLast { get; set; }
        public Nullable<int> ID_Default_Provider { get; set; }
        public Nullable<int> ID_Default_PlaceOfServiceCode { get; set; }
        public Nullable<int> ID_Default_Therapist { get; set; }
        public Nullable<int> ID_Default_Salesperson { get; set; }
        public Nullable<int> ID_Patient_Status_1 { get; set; }
        public Nullable<int> ID_Patient_Status_2 { get; set; }
        public Nullable<int> ID_Patient_Status_3 { get; set; }
        public Nullable<int> ID_Patient_Status_4 { get; set; }
        public Nullable<int> ID_Patient_Status_5 { get; set; }
        public Nullable<int> ID_Patient_Status_6 { get; set; }
        public Nullable<int> ID_Patient_Status_7 { get; set; }
        public Nullable<int> ID_Patient_Status_8 { get; set; }
        public Nullable<int> ID_Patient_Status_9 { get; set; }
        public Nullable<int> ID_Patient_Status_10 { get; set; }
        public Nullable<System.DateTime> Signature_Date { get; set; }
        public Nullable<System.DateTime> SupplierStandardDate { get; set; }
        public Nullable<System.DateTime> HIPAADate { get; set; }
        public string MedicalRecordNumber { get; set; }
        public Nullable<short> Is_A_Patient { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BirthWeight { get; set; }
        public Nullable<int> ID_Employer { get; set; }
        public string Emp_Work_Status { get; set; }
        public string Emp_Student_Status { get; set; }
        public string SpecialConsiderations { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public Nullable<int> Last_Updated_User { get; set; }
        public string ShipToCareOf { get; set; }
        public string ShipToCounty { get; set; }
        public string Directions { get; set; }
        public string Comments { get; set; }
        public string PhoneTMZ { get; set; }
        public Nullable<int> ID_Language { get; set; }
        public Nullable<short> PTNotPresentForSignature { get; set; }
        public Nullable<short> OtherIdentificationType { get; set; }
        public string OtherIdentification { get; set; }
        public Nullable<int> ID_Default_CatheterType { get; set; }
        public Nullable<System.DateTime> NoAllergiesAsOfDate { get; set; }
        public Nullable<short> DisplayCommentsInOrders { get; set; }
        public string Authorized_Contact { get; set; }
        public string Authorized_Phone { get; set; }
        public string Authorized_Drivers_License { get; set; }
        public Nullable<short> NCPDP_ResidenceCode { get; set; }
        public string Dx5 { get; set; }
        public string DXCause5 { get; set; }
        public string Dx6 { get; set; }
        public string DXCause6 { get; set; }
        public string Dx7 { get; set; }
        public string DXCause7 { get; set; }
        public string Dx8 { get; set; }
        public string DXCause8 { get; set; }
        public string Dx9 { get; set; }
        public string DXCause9 { get; set; }
        public string Dx10 { get; set; }
        public string DXCause10 { get; set; }
        public string Dx11 { get; set; }
        public string DXCause11 { get; set; }
        public string Dx12 { get; set; }
        public string DXCause12 { get; set; }
        public Nullable<short> ForeignAddr { get; set; }
        public Nullable<System.DateTime> NoOTCsAsOfDate { get; set; }
        public Nullable<System.DateTime> NoHerbalsAsOfDate { get; set; }
        public Nullable<System.DateTime> NoVitaminsAsOfDate { get; set; }
        public string Prefix_Name { get; set; }
        public string Suffix_Name { get; set; }
        public string MobilePhone { get; set; }
        public string FullName { get; set; }
        public Nullable<int> ID_Diet { get; set; }
        public string MedicalHistory { get; set; }
        public Nullable<int> ID_Ethnicity { get; set; }
    }
}
