//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Items
    {
        public int ID { get; set; }
        public int Account { get; set; }
        public short Member { get; set; }
        public Nullable<int> ID_Encounter { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> Through_Date { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public int ID_Billing_Code { get; set; }
        public Nullable<int> ID_DeliveryLocation { get; set; }
        public Nullable<int> ID_PickupLocation { get; set; }
        public int Qty { get; set; }
        public Nullable<short> UnitQty { get; set; }
        public Nullable<short> ItemType { get; set; }
        public Nullable<decimal> D_CalcUnitCost { get; set; }
        public string D_MS_PNID { get; set; }
        public string D_PkgDrugName { get; set; }
        public Nullable<short> D_DosesPerDay { get; set; }
        public Nullable<short> D_TotalDaysSupply { get; set; }
        public Nullable<decimal> PN_Unit_COGS { get; set; }
        public Nullable<int> PN_ID_Vendor { get; set; }
        public Nullable<decimal> PN_Unit_ContractAllowable { get; set; }
        public Nullable<short> TaxExemptItem { get; set; }
        public Nullable<double> TaxRateApplied { get; set; }
        public Nullable<bool> PrintPrice { get; set; }
        public Nullable<int> ID_PA { get; set; }
        public Nullable<int> ID_PASecondary { get; set; }
        public string Serial_Number { get; set; }
        public Nullable<int> ID_Pickup_Reason { get; set; }
        public Nullable<int> ID_CMN { get; set; }
        public string Condition { get; set; }
        public Nullable<int> OxygenHours { get; set; }
        public string LineComment { get; set; }
        public Nullable<int> ID_AutoClaimHold { get; set; }
        public Nullable<System.DateTime> PickupEnteredDate { get; set; }
        public Nullable<int> ID_PickupEnteredBy { get; set; }
        public Nullable<System.DateTime> ConvertToSaleDate { get; set; }
        public string ConvertToSaleModifier { get; set; }
        public Nullable<decimal> ConvertToSalePrice { get; set; }
        public Nullable<int> ConvertToSaleID_CMN { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ID_CreatedBy { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<int> ID_Changed { get; set; }
        public Nullable<int> Tag { get; set; }
        public Nullable<short> D_Cmp_IsCompounded { get; set; }
        public Nullable<short> D_Cmp_DosesPerBag { get; set; }
        public Nullable<short> D_Cmp_NumberOfBags { get; set; }
        public string ProcedureCodeOverride { get; set; }
        public Nullable<short> BCMIndicator { get; set; }
        public Nullable<int> ID_BCMItem { get; set; }
        public Nullable<short> D_RxFillNumber { get; set; }
        public Nullable<int> CreatedByOutreach { get; set; }
        public Nullable<int> ID_WOLine { get; set; }
        public Nullable<int> ID_EstLine { get; set; }
        public string UPNOverride { get; set; }
        public string UPNQualifier { get; set; }
        public string NDCOverride { get; set; }
        public Nullable<double> D_Dose { get; set; }
        public Nullable<int> D_ID_DosageFrequency { get; set; }
        public Nullable<int> D_ID_AdminRoute { get; set; }
        public string D_Cmp_CompoundDirections { get; set; }
        public string D_DoseUOM { get; set; }
        public Nullable<double> D_DrugQuantity { get; set; }
        public Nullable<int> D_Cmp_IDActiveDrugProduct { get; set; }
        public Nullable<int> D_ID_Adjudicate_Submit { get; set; }
        public Nullable<int> D_ID_Adjudicate_Respond { get; set; }
        public Nullable<decimal> UnitCOGS { get; set; }
        public Nullable<int> QtyToBillOverride { get; set; }
        public string MfgReference { get; set; }
        public Nullable<short> D_ClaimClarificationCode { get; set; }
        public Nullable<short> D_ClaimClarificationCode2 { get; set; }
        public Nullable<short> D_ClaimClarificationCode3 { get; set; }
        public Nullable<int> D_TotalDoses { get; set; }
        public Nullable<int> ID_Therapy { get; set; }
        public Nullable<System.DateTime> EquipmentPickupDate { get; set; }
    }
}
