//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UPS_WorkOrders
    {
        public int ID_WorkOrder { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public string ConfirmationNumber { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public Nullable<int> intWeight { get; set; }
        public string varReferenceNumber { get; set; }
        public Nullable<int> intPackerID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public string ShippingRecordID { get; set; }
        public string WorkOrderStr { get; set; }
        public string DateShippedStr { get; set; }
        public string CancelDateStr { get; set; }
        public int ID { get; set; }
    }
}
