//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeliveryMethod_Table
    {
        public int ID { get; set; }
        public string MethodType { get; set; }
        public string DeliveryMethod { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ID_DeletedBy { get; set; }
        public string ShippingCode { get; set; }
        public Nullable<short> MailOrderDeliveryType { get; set; }
    }
}
