//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Billing_Code_Table
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string RecType { get; set; }
        public Nullable<int> ID_Category { get; set; }
        public string Description { get; set; }
        public string NOCDescription { get; set; }
        public string Comments { get; set; }
        public string SizeComment { get; set; }
        public Nullable<short> How_To_Order { get; set; }
        public Nullable<int> ID_TypeOfService { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public Nullable<short> Warranty_Length { get; set; }
        public string Warranty_Type { get; set; }
        public Nullable<short> JACHOInterval { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ID_ChangedBy { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ID_DeletedBy { get; set; }
        public Nullable<int> ID_CreatedBy { get; set; }
    }
}
