//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Allowable_Amounts
    {
        public int ID_AllowableSet { get; set; }
        public System.DateTime AsOfDateOfService { get; set; }
        public string Procedure_Code { get; set; }
        public string StateCode { get; set; }
        public Nullable<decimal> Purchase { get; set; }
        public Nullable<decimal> Rental { get; set; }
        public Nullable<decimal> Per_Diem_Rate { get; set; }
        public Nullable<double> CostPlusPercent { get; set; }
        public short ClaimType { get; set; }
        public Nullable<short> CostPlusRule { get; set; }
        public Nullable<decimal> RetailPurchase { get; set; }
        public Nullable<decimal> RetailRental { get; set; }
        public Nullable<double> RetailCostPlusPercent { get; set; }
        public Nullable<double> CostPlusPercentRate1 { get; set; }
        public Nullable<double> CostPlusPercentRate2 { get; set; }
        public Nullable<double> CostPlusPercentRate3 { get; set; }
        public Nullable<double> CostPlusPercentRate4 { get; set; }
        public Nullable<double> RetailCostPlusPercentRate1 { get; set; }
        public Nullable<double> RetailCostPlusPercentRate2 { get; set; }
        public Nullable<double> RetailCostPlusPercentRate3 { get; set; }
        public Nullable<double> RetailCostPlusPercentRate4 { get; set; }
        public Nullable<short> PurchaseRateToUse { get; set; }
        public Nullable<double> AWPAdjPercent { get; set; }
        public Nullable<double> ASPAdjPercent { get; set; }
    }
}
