//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account_Member_Insurance
    {
        public int Account { get; set; }
        public short Member { get; set; }
        public short Sequence_Number { get; set; }
        public short Entry_Number { get; set; }
        public Nullable<short> Relationship { get; set; }
        public string Policy_Number { get; set; }
    }
}
