//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Encounters
    {
        public int ID { get; set; }
        public int Account { get; set; }
        public short Member { get; set; }
        public string Type_Of_Encounter { get; set; }
        public string Invoice_Number { get; set; }
        public string Purchase_Order_Number { get; set; }
        public Nullable<int> ID_Shipping_Method { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<int> ID_WorkOrder { get; set; }
        public Nullable<int> ID_WorkOrderCreatedBy { get; set; }
        public int ID_Incident { get; set; }
        public Nullable<System.DateTime> Referral_Date { get; set; }
        public Nullable<int> ID_Referral_Source { get; set; }
        public string ReferralContactPerson { get; set; }
        public int ID_Provider { get; set; }
        public Nullable<int> ID_Place_Of_Service { get; set; }
        public Nullable<int> ID_Referring_Doctor { get; set; }
        public Nullable<int> ID_Salesperson { get; set; }
        public Nullable<System.DateTime> Admission_Date { get; set; }
        public Nullable<System.DateTime> Discharge_Date { get; set; }
        public string Emergency { get; set; }
        public string Notes { get; set; }
        public string ShippingRecordID { get; set; }
        public string ShippingConfirmationNumber { get; set; }
        public string ExternalReference { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ID_CreatedBy { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public Nullable<int> Last_Updated_User { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
        public Nullable<int> Deleted_User { get; set; }
        public Nullable<int> ID_Est { get; set; }
        public string ShipToCareOf { get; set; }
        public string ShipToAddress_1 { get; set; }
        public string ShipToAddress_2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToZip { get; set; }
        public string ShipToPhone { get; set; }
        public string ShipToCounty { get; set; }
        public Nullable<System.DateTime> D_AdminStartDate { get; set; }
        public Nullable<System.DateTime> D_AdminEndDate { get; set; }
        public Nullable<int> ID_Rendering_Doctor { get; set; }
        public Nullable<short> D_ReplacementRxOrder { get; set; }
    }
}
