//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CSRComplaintLog_Attachments
    {
        public int ID { get; set; }
        public Nullable<int> Account { get; set; }
        public Nullable<int> ComplaintId { get; set; }
        public string FileName { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
    }
}
