//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CSRInsDetail
    {
        public string id { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
        public string VerifiedThrough { get; set; }
        public bool NameMatched { get; set; }
        public bool NameNotMatched { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public string BenefitPlan { get; set; }
        public string LevelOfCare { get; set; }
        public string COBnOtherIns { get; set; }
        public bool InNetwork { get; set; }
        public bool OutofNetwork { get; set; }
        public Nullable<decimal> Deductible { get; set; }
        public Nullable<decimal> OutofPocketMax { get; set; }
        public string CopayCoins { get; set; }
        public bool CopayCoinsWaived { get; set; }
        public bool CopayCoinsNotWaived { get; set; }
        public bool DME { get; set; }
        public bool Medical { get; set; }
        public bool Pharmacy { get; set; }
        public bool Medicaid { get; set; }
        public bool Medicare { get; set; }
        public bool Other { get; set; }
        public string HCPCnQtyLimitations { get; set; }
        public bool HHE { get; set; }
        public bool Hospice { get; set; }
        public bool Hospital { get; set; }
        public bool NursingHome { get; set; }
        public bool MemEnrollNone { get; set; }
    }
}
