//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account_Note
    {
        public int ID { get; set; }
        public Nullable<int> Account { get; set; }
        public Nullable<short> Member { get; set; }
        public string NoteHeading { get; set; }
        public Nullable<System.DateTime> NoteCreateDate { get; set; }
        public Nullable<int> NoteCreatedBy { get; set; }
        public Nullable<int> Tag { get; set; }
        public Nullable<int> PSR_ID { get; set; }
        public Nullable<short> SystemRecordType { get; set; }
        public Nullable<int> ID_NoteLibrary { get; set; }
    }
}
