//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Name_PayerTypes
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<short> MedicareOxygenRules { get; set; }
        public Nullable<short> MedicareOxygen4LPMRule { get; set; }
        public Nullable<short> MedicarePenRules { get; set; }
        public Nullable<short> InsuranceQuestionsFormat { get; set; }
        public Nullable<short> CappedRentalMonths { get; set; }
        public Nullable<short> CappedMaintMonths { get; set; }
        public Nullable<double> CappedReductionRate { get; set; }
        public Nullable<short> CappedRentalLetterMonth { get; set; }
        public Nullable<short> CappedRentalLetterFormat { get; set; }
        public Nullable<short> ReportColumn { get; set; }
        public Nullable<short> EDI_SendCMNs { get; set; }
        public Nullable<short> HCFA1500PayerClassification { get; set; }
        public Nullable<short> HCFA1500PayerClassificationMark { get; set; }
        public Nullable<short> HCFA1500PrintPayerAddress { get; set; }
        public Nullable<short> HCFA1500PrintPatientAddress { get; set; }
        public Nullable<short> HCFA1500InsuredAddressSAMEIfPrimary { get; set; }
        public Nullable<short> HCFA1500OtherInsuredInformation { get; set; }
        public Nullable<short> HCFA1500ReservedForLocal { get; set; }
        public Nullable<short> HCFA1500SecondaryPayerInfo { get; set; }
        public Nullable<short> HCFA1500PatientSignatureOnFile { get; set; }
        public Nullable<short> HCFA1500InsuredSignatureOnFile { get; set; }
        public Nullable<short> HCFA1500ReferringDoctorInfo { get; set; }
        public Nullable<short> HCFA1500ReferringDoctorID { get; set; }
        public Nullable<short> HCFA1500HospitalDates { get; set; }
        public Nullable<short> HCFA1500ChargeAmount { get; set; }
        public Nullable<short> HCFA1500QtyUnits { get; set; }
        public Nullable<short> HCFA1500ShowAssignment { get; set; }
        public Nullable<short> HCFA1500ShowPaidAmount { get; set; }
        public Nullable<short> HCFA1500ShowBalanceAmount { get; set; }
        public Nullable<short> HCFA1500AllowReplacementClaims { get; set; }
        public Nullable<short> HCFA1500EmgInfo { get; set; }
        public Nullable<short> HCFA1500COBInfo { get; set; }
        public Nullable<short> HCFA1500LocalUseBoxK { get; set; }
        public Nullable<short> HCFA1500SupplierAddress { get; set; }
        public Nullable<short> RentalServiceToDateRule { get; set; }
        public Nullable<short> DailyRentalServiceDateRule { get; set; }
        public string Modifier_Rental { get; set; }
        public string Modifier_NewPurchase { get; set; }
        public string Modifier_UsedPurchase { get; set; }
        public Nullable<short> ModifierPurchaseRule { get; set; }
        public Nullable<short> CMNModifiersOnClaims { get; set; }
        public Nullable<short> PriorAuthDischargeGracePeriod { get; set; }
        public Nullable<short> PriorAuthFormat_NOTUSED { get; set; }
        public Nullable<short> RequireAttachedCMN { get; set; }
        public Nullable<short> PaysForOxygenContents { get; set; }
        public Nullable<short> MedicareABNRules { get; set; }
        public Nullable<short> NoCappedRentalModifiers { get; set; }
        public Nullable<short> HCFA1500ProcModDx { get; set; }
        public Nullable<short> HCFA1500TOS { get; set; }
        public Nullable<short> CappedRentalDRA2005 { get; set; }
        public Nullable<short> HCFA1500SupplierNumber { get; set; }
        public Nullable<short> DailyRentalBillAtEOM { get; set; }
        public Nullable<short> HCFA1500EPSDTFamilyPlan { get; set; }
        public Nullable<short> HCFA1500ServiceFacilityLocation { get; set; }
        public Nullable<short> RequireAOBSignatureDate { get; set; }
        public Nullable<short> HCFA1500SupplierSignature { get; set; }
        public Nullable<short> HCFA1500RenderingProviderID { get; set; }
        public Nullable<short> CappedOxygen { get; set; }
        public Nullable<short> HCFA1500OtherHealthBenPlan { get; set; }
        public Nullable<short> ClaimsWithSameDOSMonthYear { get; set; }
        public Nullable<short> ModifierDiabeticShippingRule { get; set; }
        public Nullable<short> HCFA1500FedTaxNumber { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<int> ID_ChangedBy { get; set; }
        public Nullable<short> CappedOxygen_Months { get; set; }
        public Nullable<short> CappedOxygen_MaintConc { get; set; }
        public Nullable<short> CappedOxygen_MaintStat { get; set; }
        public Nullable<short> CappedOxygen_MaintPort { get; set; }
        public Nullable<short> CappedOxygen_MaintMonths { get; set; }
        public Nullable<System.DateTime> CappedOxygenRuleStartDate { get; set; }
        public Nullable<short> FORM1500AddlClaimInfo { get; set; }
        public string Replacement_Modifier { get; set; }
        public Nullable<short> Replacement_SuppressNU { get; set; }
        public Nullable<short> HCFA1500Box32Number { get; set; }
    }
}
