//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payer_Table
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone_Number { get; set; }
        public string Fax_Number { get; set; }
        public string Email { get; set; }
        public string Internet { get; set; }
        public string Contact { get; set; }
        public string Comments { get; set; }
        public string PAAddress_1 { get; set; }
        public string PAAddress_2 { get; set; }
        public string PACity { get; set; }
        public string PAState { get; set; }
        public string PAZip { get; set; }
        public string PAPhone_Number { get; set; }
        public string PAFax_Number { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public Nullable<short> Insurance_Type { get; set; }
        public Nullable<int> ID_PayerType { get; set; }
        public Nullable<int> ID_Procedure_Group { get; set; }
        public Nullable<int> ID_Allowable { get; set; }
        public Nullable<int> ID_Form { get; set; }
        public Nullable<int> ID_DeliveryChargeBillCode { get; set; }
        public Nullable<int> ID_DispenseFeeBillCode { get; set; }
        public Nullable<int> ID_DispenseFeeCategory_1 { get; set; }
        public Nullable<int> ID_DispenseFeeCategory_2 { get; set; }
        public Nullable<int> ID_DispenseFeeCategory_3 { get; set; }
        public Nullable<int> ID_DispenseFeeCategory_4 { get; set; }
        public Nullable<int> ID_DispenseFeeCategory_5 { get; set; }
        public Nullable<int> ID_DispenseFeeCategory_6 { get; set; }
        public Nullable<short> AutoCappedModifier { get; set; }
        public string OCNA { get; set; }
        public Nullable<int> ID_Terms { get; set; }
        public string EMC_Payer_ID { get; set; }
        public string EMC_PayerPlanID { get; set; }
        public string EMC_ClaimOfficeID { get; set; }
        public string EMC_ClaimFilingIndicator { get; set; }
        public Nullable<short> EMC_Send2310BLoop { get; set; }
        public string ExternalReference { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<int> ID_ChangedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ID_DeletedBy { get; set; }
        public Nullable<short> NoPurchaseModforJ { get; set; }
        public Nullable<int> ClaimReviewFormat { get; set; }
        public Nullable<short> SubmitAllPreviousInsurances { get; set; }
        public Nullable<short> OxygenOncePerMonth { get; set; }
        public Nullable<short> CappedModifiersOnAllRentals { get; set; }
        public Nullable<short> NTEPurchaseInfoOnRentals { get; set; }
        public Nullable<short> SubmitAllowableAmount { get; set; }
        public Nullable<short> EMC_Suppress2420CLoop { get; set; }
        public string BillToName { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToCity { get; set; }
        public string BillToState { get; set; }
        public string BillToZip { get; set; }
        public string BillToPhone { get; set; }
        public string BillToFax { get; set; }
        public string BillToContact { get; set; }
        public string ContactTitle { get; set; }
        public string ContactEmail { get; set; }
        public string BillToContactTitle { get; set; }
        public string BillToContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string BillToContactPhone { get; set; }
        public string COBA { get; set; }
        public Nullable<short> EMC_AlwaysAdjDate2430Loop { get; set; }
        public Nullable<short> DateFormatOnClaims { get; set; }
        public Nullable<short> EMC_Send2320LoopMOA { get; set; }
        public Nullable<short> IgnoreProcOverrideTable { get; set; }
        public string GLNumber { get; set; }
        public Nullable<short> WOIfPrimaryExceedsAllowable { get; set; }
        public Nullable<int> ID_PAForm { get; set; }
        public Nullable<short> SubmitLegacyNumbers { get; set; }
        public Nullable<short> ArrearsBilling { get; set; }
        public Nullable<int> ID_Form_Crossovers { get; set; }
        public string EMC_Payer_ID_835 { get; set; }
        public Nullable<short> EMC_SubmitSSNIfPresent { get; set; }
        public Nullable<short> NTEDescriptionForAllItems { get; set; }
        public Nullable<short> EMC_Suppress2420ELoop { get; set; }
        public Nullable<double> DefaultCoPayPercent { get; set; }
        public Nullable<short> EligDontUpdateAccountInsurance { get; set; }
        public Nullable<short> SplitEOYBilling { get; set; }
        public string EMC_InsuranceTypeCode { get; set; }
        public Nullable<int> EMC_DontRemoveCharPolicyNumber { get; set; }
        public Nullable<short> EMC_SubmitItemSerialNumberIfPresent { get; set; }
        public string EMC_Payer_ID_Eligibility { get; set; }
        public string EMC_Payer_EligibilityIdentifier { get; set; }
        public Nullable<short> EMC_EligSendCardIssueDate { get; set; }
        public Nullable<short> TimelyFilingDays { get; set; }
        public Nullable<short> RequirePECOS { get; set; }
        public Nullable<short> EMC_Send2010ABLoop { get; set; }
        public Nullable<int> ID_EOBForm_MedicarePrimary { get; set; }
        public Nullable<int> ID_EOBForm_NonMedicarePrimary { get; set; }
        public Nullable<short> EMC_Send2310CLoop { get; set; }
        public string Pharmacy_ProcessorControlNumber { get; set; }
        public string Pharmacy_BinNumber { get; set; }
        public string Pharmacy_CertificationID { get; set; }
        public Nullable<short> EMC_PrimaryOnlyClaims { get; set; }
        public Nullable<short> EMC_EligibilityMethods { get; set; }
        public Nullable<short> EMC_Send2310ALoop { get; set; }
        public Nullable<short> EMC_Send2410Loop { get; set; }
        public Nullable<short> CombinedHCPCMustMatchDOS { get; set; }
        public Nullable<short> EMC_Autopost_ExcludeQtyCheck { get; set; }
        public string TimelyFilingModifier { get; set; }
        public Nullable<decimal> DispenseFeeRate { get; set; }
        public Nullable<short> DispenseFeeAlwaysApply { get; set; }
        public Nullable<short> Pharmacy_SubmitMethod { get; set; }
        public Nullable<short> Pharmacy_GrossAmt_Calc_Rule { get; set; }
        public Nullable<short> NCPDP_PrescriberQualifierEZ { get; set; }
        public Nullable<short> NCPDP_PCPQualifier2E { get; set; }
        public Nullable<short> NCPDP_ProviderQualifierE9 { get; set; }
        public Nullable<short> NCPDP_ExcludeCompoundSegment { get; set; }
        public Nullable<short> EMC_EligSendServiceDate { get; set; }
        public string DispenseFeeProcedure_Init { get; set; }
        public string DispenseFeeProcedure_30Days { get; set; }
        public string DispenseFeeProcedure_After30 { get; set; }
        public Nullable<int> ID_PerDiemSchedule { get; set; }
        public Nullable<short> EMC_Autopost_NOC_ToException { get; set; }
        public Nullable<short> GenerateTax { get; set; }
        public Nullable<short> IncludeNonActiveDrugsInCompound { get; set; }
        public Nullable<short> PerDiemNeverAutoAdd { get; set; }
        public Nullable<short> PerDiemAutoHoldAllOrdersWithMultiple { get; set; }
        public Nullable<short> AppealLimitDays { get; set; }
        public Nullable<short> EMC_Send2300LoopPWK { get; set; }
        public Nullable<short> EMC_SendShipAddress2010 { get; set; }
        public Nullable<int> ID_CreatedBy { get; set; }
        public Nullable<short> RequiresFTFRules { get; set; }
        public Nullable<short> ClaimDaysToAdvance { get; set; }
        public Nullable<short> NeverBillNonActiveDrugsOfCompound { get; set; }
        public Nullable<System.DateTime> EMC_ICD10_EffectiveDate { get; set; }
        public Nullable<int> ID_Form_Pharmacy { get; set; }
        public Nullable<short> EMC_SubmitQtyOverThree { get; set; }
        public Nullable<short> IsPayerValid { get; set; }
        public Nullable<short> EMC_EligDOMtoSend { get; set; }
        public string EMC_EligServiceTypeCodes { get; set; }
        public Nullable<decimal> DispenseFeeRate30DaySupply { get; set; }
        public Nullable<decimal> DispenseFeeRate90DaySupply { get; set; }
        public Nullable<short> CrossoverWaitPeriodOverride { get; set; }
        public Nullable<short> Sequestration { get; set; }
        public Nullable<int> ID_OperatorTeam { get; set; }
        public Nullable<short> AutoPostZeroBalanceClaim { get; set; }
        public Nullable<short> EMC_SendNOCDescOnly2400Loop { get; set; }
        public Nullable<short> SuppressPriceOnWorkOrder { get; set; }
        public Nullable<short> NCPDP_C3 { get; set; }
        public Nullable<short> NCPDP_C9 { get; set; }
        public Nullable<short> NCPDP_BasisOfCost_DN { get; set; }
        public Nullable<short> NCPDP_UsualCustomary_DQ { get; set; }
        public Nullable<short> BenefitPlan { get; set; }
        public Nullable<short> EMC_Autopost_NoAddlMACPosting { get; set; }
        public Nullable<short> Pharmacy_TPN_BillingMethod { get; set; }
        public Nullable<short> NCPDP_WE_DxMaxCount { get; set; }
        public Nullable<double> AllowablePercentOfCharge { get; set; }
        public Nullable<short> EMC_AutoPostPaysBeforePrimary { get; set; }
        public Nullable<int> ID_ContractualCopayAllowable { get; set; }
        public Nullable<short> EMC_EligSendN3N4 { get; set; }
        public Nullable<short> AdvanceShippingThreshold { get; set; }
        public Nullable<short> DoNotAutoconfirmWorkOrders { get; set; }
        public Nullable<short> SpanDateOnSingleDrug { get; set; }
    }
}
