//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CSRComplaintLog
    {
        public int id { get; set; }
        public Nullable<int> Account { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string PayerType { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<bool> Damaged { get; set; }
        public Nullable<bool> Driver { get; set; }
        public Nullable<bool> WrongProductShipped { get; set; }
        public Nullable<bool> QualityOfProdut { get; set; }
        public Nullable<bool> WrongArea { get; set; }
        public Nullable<bool> MissingProduct { get; set; }
        public string FedExTxt { get; set; }
        public Nullable<bool> ProductIncrease { get; set; }
        public Nullable<bool> ProductMispick { get; set; }
        public Nullable<bool> ProductDefective { get; set; }
        public string ProductTxt { get; set; }
        public Nullable<bool> ImpoliteORoffensive { get; set; }
        public Nullable<bool> HoldTimes { get; set; }
        public string customerServiceTxt { get; set; }
        public string OtherTxt { get; set; }
        public string ComplaintHasBeen { get; set; }
        public string Product { get; set; }
        public string DeliveryCompany { get; set; }
        public string BCNProvider { get; set; }
        public bool Other { get; set; }
        public bool BCNProviderIssue { get; set; }
        public bool InsLimitGuidelines { get; set; }
        public bool PhysicianIssue { get; set; }
        public bool NeverRecivedSupplies { get; set; }
        public bool NoFollowUpWithMem { get; set; }
        public bool ReturnedFromVM { get; set; }
        public bool NoFollowUp { get; set; }
        public bool Website { get; set; }
        public bool VirtualCallBack { get; set; }
        public bool SAJamesSelfService { get; set; }
        public bool SAJamesPhonePromts { get; set; }
        public bool VPaymentCalles { get; set; }
        public bool VConfirmationCalls { get; set; }
        public bool DidntFollowDelIns { get; set; }
        public Nullable<System.DateTime> ComplaintDate { get; set; }
        public Nullable<System.DateTime> ResolutionDate { get; set; }
        public Nullable<System.DateTime> InitialRespDate { get; set; }
        public Nullable<System.DateTime> WrittenRespDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<bool> Call { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> Fax { get; set; }
        public Nullable<bool> Mail { get; set; }
        public Nullable<bool> CallRcvdWebsite { get; set; }
        public Nullable<bool> SocialMedia { get; set; }
        public Nullable<bool> InsCompany { get; set; }
        public Nullable<bool> CallRcvdOther { get; set; }
        public Nullable<bool> ComplaintProduct { get; set; }
        public Nullable<bool> ComplaintShipping { get; set; }
        public Nullable<bool> ComplaintService { get; set; }
        public Nullable<bool> ComplaintSmartAction { get; set; }
        public string Resolution { get; set; }
        public Nullable<bool> Survey { get; set; }
        public bool Compliance { get; set; }
        public bool CustomerService { get; set; }
        public bool Discrimination { get; set; }
        public bool HealthPlan { get; set; }
        public bool ProductDefectiveQuality { get; set; }
        public bool ShippingUSPS { get; set; }
        public bool ShippingWarehouse { get; set; }
        public bool SmartAction { get; set; }
        public bool TextMessaging { get; set; }
        public bool WebsitePortal { get; set; }
        public bool BloodPressureMonitors { get; set; }
        public bool BreastPumps { get; set; }
        public bool ContGlucoseMonitoring { get; set; }
        public bool DiabeticTestSup { get; set; }
        public bool EnteralNutrition { get; set; }
        public bool ExternalDefibrillator { get; set; }
        public bool IncontinenceSupplies { get; set; }
        public bool InsulinPumpsSupplies { get; set; }
        public bool InsSyrPenNeed { get; set; }
        public bool OstomySupplies { get; set; }
        public bool PleurXDrainSys { get; set; }
        public bool PTINRTesting { get; set; }
        public bool TENSUnitSup { get; set; }
        public bool UrologicalSupplies { get; set; }
        public bool WoundCareSupplies { get; set; }
        public bool OtherUnsureSupplies { get; set; }
        public bool BDI { get; set; }
        public bool BPnBPM { get; set; }
        public bool CallCenter { get; set; }
        public bool CSRAssessment { get; set; }
        public bool DynamicSynergy { get; set; }
        public bool Enteral { get; set; }
        public bool HGS { get; set; }
        public bool InsulinPumpCGM { get; set; }
        public bool MedicalDocuments { get; set; }
        public bool NewAccountTeam { get; set; }
        public bool Nurses { get; set; }
        public bool QualityAssurance { get; set; }
        public bool Shipping { get; set; }
        public bool THC { get; set; }
        public bool Troy { get; set; }
        public bool Verification { get; set; }
        public bool WebSupport { get; set; }
        public bool WoundCareOstomyTENS { get; set; }
        public bool OtherUnsureTeam { get; set; }
        public string PendingResolution { get; set; }
        public bool ProcessDelay { get; set; }
        public bool PhoneFaxIssues { get; set; }
        public bool ITHelpDesk { get; set; }
    }
}
