//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssessmentDue_Attempts
    {
        public int ID { get; set; }
        public Nullable<int> Account { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public string State { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Duration { get; set; }
        public bool HasPullOns { get; set; }
        public bool Attempt1st { get; set; }
        public bool Attempt2nd { get; set; }
        public bool Attempt3rd { get; set; }
        public bool isSetToHold { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
