//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inv_VendorProduct_Table
    {
        public int ID { get; set; }
        public int ID_Vendor { get; set; }
        public int ID_Product { get; set; }
        public string VendorPartNumber { get; set; }
        public string VendorProductDescription { get; set; }
        public Nullable<int> ID_UOM { get; set; }
        public Nullable<short> UOMCount { get; set; }
        public Nullable<decimal> UOMCost { get; set; }
        public Nullable<short> PreferredVendor { get; set; }
        public string POUOMTextOverride { get; set; }
        public Nullable<short> LabelsPerUnit { get; set; }
        public Nullable<short> AutoPOOverrideVendor { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<int> ID_ChangedBy { get; set; }
        public Nullable<System.DateTime> LastPriceChange { get; set; }
        public Nullable<int> ID_PriceChangedBy { get; set; }
        public string Prev_VendorPartNumber { get; set; }
        public string Prev_VendorProductDescription { get; set; }
        public Nullable<int> Prev_ID_UOM { get; set; }
        public Nullable<short> Prev_UOMCount { get; set; }
        public Nullable<decimal> Prev_UOMCost { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ID_CreatedBy { get; set; }
    }
}
