//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PS_WorkOrderLine
    {
        public int ID { get; set; }
        public int Account { get; set; }
        public int ID_PlanOfService { get; set; }
        public int ID_PS_WorkOrder { get; set; }
        public short WorkOrderType { get; set; }
        public Nullable<int> ID_RxDoctor { get; set; }
        public Nullable<int> ID_CMN { get; set; }
        public Nullable<int> ID_PAPrimary { get; set; }
        public Nullable<int> ID_PASecondary { get; set; }
        public Nullable<int> ID_Billing_Code { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> QtyOrdered { get; set; }
        public Nullable<int> QtyShipped { get; set; }
        public Nullable<int> QtyBackOrdered { get; set; }
        public Nullable<short> UnitQty { get; set; }
        public bool SalesTaxExempt { get; set; }
        public string SizeComment { get; set; }
        public string ItemNote { get; set; }
        public Nullable<short> ItemType { get; set; }
        public string Frequency { get; set; }
        public string ManufacturerSerialNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> ID_Item { get; set; }
        public Nullable<int> ID_Pickup_Reason { get; set; }
        public Nullable<int> ID_ProductExchange { get; set; }
        public string SerialNumberExchange { get; set; }
        public Nullable<int> OxygenHours { get; set; }
        public string HCPC { get; set; }
        public string Modifier1 { get; set; }
        public string Modifier2 { get; set; }
        public string Modifier3 { get; set; }
        public string Modifier4 { get; set; }
        public Nullable<int> PlannedIDPayer { get; set; }
        public string HistoryNote { get; set; }
        public Nullable<int> Tag { get; set; }
        public Nullable<bool> ApprovedForBilling { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ID_DeletedBy { get; set; }
        public string EDIConfirmationNumber { get; set; }
        public Nullable<System.DateTime> EDIImageLastPrintDate { get; set; }
        public Nullable<int> ID_OrigWOLineFromBO { get; set; }
        public string LineNarrative { get; set; }
        public Nullable<int> ID_QuoteLine { get; set; }
        public Nullable<decimal> PN_Unit_COGS { get; set; }
        public Nullable<int> PN_ID_Vendor { get; set; }
        public Nullable<decimal> PN_Unit_ContractAllowable { get; set; }
        public Nullable<double> PN_Unit_ContractCostPlusPercent { get; set; }
        public Nullable<short> PN_Unit_ContractCostPlusRule { get; set; }
        public Nullable<decimal> PN_Unit_ContractPrice { get; set; }
        public Nullable<short> RepeatNarrativeForRentals { get; set; }
        public Nullable<double> PN_Unit_ContractRetailPlusPercent { get; set; }
        public Nullable<int> QtyShippedTotal { get; set; }
        public Nullable<decimal> CalculatedUnitCoPay { get; set; }
        public Nullable<decimal> CoPayPaymentAmount { get; set; }
        public Nullable<short> OxygenMonthsSupply { get; set; }
        public Nullable<decimal> OriginalUnitPrice { get; set; }
        public Nullable<int> ID_AutoClaimHoldReason { get; set; }
        public Nullable<short> DoNotRemoveFromStock { get; set; }
        public Nullable<short> ProductMacroComponent { get; set; }
        public Nullable<short> DoNotBillProductMacroComponent { get; set; }
        public Nullable<decimal> D_CalcUnitCost { get; set; }
        public string D_MS_PNID { get; set; }
        public string D_PkgDrugName { get; set; }
        public Nullable<short> D_NumberOfLabels { get; set; }
        public Nullable<short> D_DosesPerDay { get; set; }
        public Nullable<short> D_TotalDaysSupply { get; set; }
        public Nullable<short> d_cmp_DosesPerBag_old { get; set; }
        public Nullable<short> D_Cmp_NumberOfBags { get; set; }
        public string ProcedureCodeOverride { get; set; }
        public Nullable<short> WasAutoCreatedFromOutReach { get; set; }
        public Nullable<short> D_PrintSyringeLabel { get; set; }
        public Nullable<short> D_UsedAsIfPrimaryTherapy { get; set; }
        public Nullable<int> ID_EstLine { get; set; }
        public Nullable<decimal> D_Cmp_DrugUnitPrice { get; set; }
        public Nullable<System.DateTime> D_RxDrug_Fill_StableUntilDate { get; set; }
        public Nullable<double> StateTaxRate { get; set; }
        public Nullable<decimal> StateTaxAmount { get; set; }
        public Nullable<double> CountyTaxRate { get; set; }
        public Nullable<decimal> CountyTaxAmount { get; set; }
        public Nullable<double> CityTaxRate { get; set; }
        public Nullable<decimal> CityTaxAmount { get; set; }
        public Nullable<double> StateCopayTaxRate { get; set; }
        public Nullable<decimal> StateCopayTaxAmount { get; set; }
        public Nullable<double> CountyCopayTaxRate { get; set; }
        public Nullable<decimal> CountyCopayTaxAmount { get; set; }
        public Nullable<double> CityCopayTaxRate { get; set; }
        public Nullable<decimal> CityCopayTaxAmount { get; set; }
        public Nullable<short> D_DoseScheduleDay1 { get; set; }
        public Nullable<short> D_DoseScheduleDay2 { get; set; }
        public Nullable<short> D_DoseScheduleDay3 { get; set; }
        public Nullable<short> D_DoseScheduleDay4 { get; set; }
        public Nullable<short> D_DoseScheduleDay5 { get; set; }
        public Nullable<short> D_DoseScheduleDay6 { get; set; }
        public Nullable<short> D_DoseScheduleDay7 { get; set; }
        public Nullable<int> ID_DiscountPlan { get; set; }
        public Nullable<decimal> CalcUnitPriceDiscount { get; set; }
        public Nullable<int> D_ID_Adjudicate_Submit { get; set; }
        public Nullable<int> D_ID_Adjudicate_Respond { get; set; }
        public Nullable<short> D_DrugEntryType { get; set; }
        public Nullable<double> D_TPNOrderedAdminVol_ml { get; set; }
        public Nullable<double> D_TPNOverfillVol_ml { get; set; }
        public Nullable<short> D_TPNLipidsIndicator { get; set; }
        public Nullable<short> D_TPNAdditivePool { get; set; }
        public Nullable<double> D_TPNOverfillPercent { get; set; }
        public Nullable<double> D_TPNInfusionDurationHrs { get; set; }
        public Nullable<double> D_TPNTaperUpHrs { get; set; }
        public Nullable<double> D_TPNTaperDownHrs { get; set; }
        public Nullable<short> D_TPNQSWithWaterAdditive { get; set; }
        public Nullable<short> D_TPNQSWithWaterLipids { get; set; }
        public Nullable<short> D_TPN_Calc_KCal_Protein { get; set; }
        public Nullable<short> D_TPN_Calc_KCal_Carbohydrates { get; set; }
        public Nullable<short> D_TPN_Calc_KCal_Fat { get; set; }
        public string Compliance_DeviceCode { get; set; }
        public Nullable<short> D_DispensedPkgQty { get; set; }
        public Nullable<double> QtyToBillOverride { get; set; }
        public Nullable<int> NWA_OrderLineID { get; set; }
        public Nullable<int> D_ID_Adjudicate_RespondReject { get; set; }
        public Nullable<decimal> D_DispensingFee { get; set; }
        public Nullable<System.DateTime> HDMSMobileConfirmDate { get; set; }
        public Nullable<System.DateTime> D_TPN_CompounderFileCreateDate { get; set; }
        public Nullable<int> D_TPN_CompounderFileCreatedByID { get; set; }
        public Nullable<short> D_ClaimClarificationCode { get; set; }
        public Nullable<double> D_TPNAdditiveVol_ml { get; set; }
        public Nullable<System.DateTime> D_DIScreenBypassDate { get; set; }
        public Nullable<int> D_DIScreenBypassBy_ID { get; set; }
        public Nullable<short> D_ClaimClarificationCode2 { get; set; }
        public Nullable<short> D_ClaimClarificationCode3 { get; set; }
        public Nullable<short> HDMSMobileItemLoaded { get; set; }
        public Nullable<double> D_DrugQty { get; set; }
        public string D_TPN_DosingWeight { get; set; }
        public Nullable<System.DateTime> D_TPN_rPH_Approval_1_Date { get; set; }
        public Nullable<int> D_TPN_rPH_Approval_1_IDOperator { get; set; }
        public Nullable<System.DateTime> D_TPN_rPH_Approval_2_Date { get; set; }
        public Nullable<int> D_TPN_rPH_Approval_2_IDOperator { get; set; }
        public Nullable<double> D_TPN_TotalProteins { get; set; }
        public Nullable<double> D_TPN_TotalCarbohydrates { get; set; }
        public Nullable<double> D_TPN_TotalLipids { get; set; }
        public Nullable<double> D_TPN_TotalAminoAcidPercent { get; set; }
        public Nullable<double> D_TPN_TotalCarbohydratePercent { get; set; }
        public string D_TPN_DosingComment { get; set; }
        public Nullable<int> D_TotalDoses { get; set; }
        public Nullable<short> D_TotalAdminDays { get; set; }
        public Nullable<System.DateTime> RentalTerminationDate { get; set; }
    }
}
