//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transaction_File
    {
        public int ID { get; set; }
        public int ID_Encounter { get; set; }
        public int ID_Item { get; set; }
        public int ID_Bill { get; set; }
        public int ID_Claim { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public int Transaction_Number { get; set; }
        public short Transaction_Type { get; set; }
        public decimal Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ID_Adjustment_Reason { get; set; }
        public Nullable<System.DateTime> Void_Date { get; set; }
        public Nullable<short> Void_Operator { get; set; }
    }
}
