//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Rejection_Report
    {
        public Nullable<int> ID_Bill { get; set; }
        public Nullable<int> Current_ClaimID { get; set; }
        public Nullable<System.DateTime> ClaimDateChanged { get; set; }
        public Nullable<System.DateTime> RejectionDate { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> Billing_Date { get; set; }
        public int Qty { get; set; }
        public int ID_Billing_Code { get; set; }
        public string BillingCode { get; set; }
        public string BillingCodeDesc { get; set; }
        public string HCPC { get; set; }
        public Nullable<int> ID_CMN { get; set; }
        public Nullable<int> ID_PA { get; set; }
        public Nullable<short> ItemType { get; set; }
        public int Account { get; set; }
        public short Member { get; set; }
        public string First_Name { get; set; }
        public string Middle { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> Deceased { get; set; }
        public string Social_Security { get; set; }
        public int ID_Provider { get; set; }
        public string ProviderName { get; set; }
        public string ProviderNPI { get; set; }
        public string ProviderTaxID { get; set; }
        public Nullable<decimal> Balance_OnBill { get; set; }
        public Nullable<int> ID_NPCode1 { get; set; }
        public string NPCode1 { get; set; }
        public string NPDesc1 { get; set; }
        public string NPHowTo1 { get; set; }
        public Nullable<int> ID_NPCode2 { get; set; }
        public string NPCode2 { get; set; }
        public string NPDesc2 { get; set; }
        public Nullable<int> ID_NPCode3 { get; set; }
        public string NPCode3 { get; set; }
        public string NPDesc3 { get; set; }
        public Nullable<int> ID_NPCode4 { get; set; }
        public string NPCode4 { get; set; }
        public string NPDesc4 { get; set; }
        public Nullable<int> ID_NPCode5 { get; set; }
        public string NPCode5 { get; set; }
        public string NPDesc5 { get; set; }
        public Nullable<int> ID_Payer { get; set; }
        public Nullable<int> ID_NPCode6 { get; set; }
        public string NPCode6 { get; set; }
        public string NPDesc6 { get; set; }
        public Nullable<int> ID_NPCode7 { get; set; }
        public string NPCode7 { get; set; }
        public string NPDesc7 { get; set; }
        public Nullable<int> ID_NPCode8 { get; set; }
        public string NPCode8 { get; set; }
        public string NPDesc8 { get; set; }
        public string RemittanceCode1 { get; set; }
        public string RemittanceCode2 { get; set; }
        public string RemittanceCode3 { get; set; }
        public string RemittanceCode4 { get; set; }
        public string RemittanceCode5 { get; set; }
        public string RemittanceCode6 { get; set; }
        public string ThisPayerName { get; set; }
        public Nullable<int> ID_PayerType { get; set; }
        public Nullable<int> ID_Procedure_Group { get; set; }
        public string ThisPayerPolicyNumber { get; set; }
        public string ThisPayerGroupNumber { get; set; }
        public string ThisPayerPhoneNumber { get; set; }
        public string Dx1 { get; set; }
        public string Dx1Desc { get; set; }
        public Nullable<int> ID_Doctor { get; set; }
        public string DoctorLastName { get; set; }
        public string DoctorFirstName { get; set; }
        public string DoctorDegree { get; set; }
        public string DoctorPhone { get; set; }
        public Nullable<int> Tx_Number { get; set; }
        public Nullable<int> ID_Status_Code_1 { get; set; }
        public Nullable<int> ID_Status_Code_2 { get; set; }
        public Nullable<int> ID_Status_Code_3 { get; set; }
        public Nullable<int> ID_Status_Code_4 { get; set; }
        public Nullable<int> ID_Status_Code_5 { get; set; }
        public Nullable<int> ID_Status_Code_6 { get; set; }
        public Nullable<int> ID_Status_Code_7 { get; set; }
        public Nullable<int> ID_Status_Code_8 { get; set; }
        public Nullable<int> ID_Status_Code_9 { get; set; }
        public Nullable<int> ID_Status_Code_10 { get; set; }
        public string ProviderNumber { get; set; }
        public int ID_HoldStatus { get; set; }
        public string HistoryRecType { get; set; }
        public Nullable<System.DateTime> EMC_ICD10_EffectiveDate { get; set; }
        public string DoctorNPI { get; set; }
    }
}
