//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrdersReleased
    {
        public int worID { get; set; }
        public Nullable<int> worID_WorkOrder { get; set; }
        public Nullable<System.DateTime> worReleasedDate { get; set; }
        public string worReleasedBy { get; set; }
        public string worHoldReasonWhenReleased { get; set; }
        public Nullable<byte> worReleaseType { get; set; }
    }
}
