//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllProdQtySubstitution_table
    {
        public int RowId { get; set; }
        public int Account { get; set; }
        public int WorkOrder { get; set; }
        public string oldProdCode { get; set; }
        public Nullable<int> oldQuantity { get; set; }
        public string newProdCode { get; set; }
        public Nullable<int> newQuantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
