//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public int Id { get; set; }
        public int AccountNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int CallTypeId { get; set; }
        public string CallStatus { get; set; }
        public System.DateTime CallTime { get; set; }
        public string CallerId { get; set; }
        public string SpokeWith { get; set; }
        public string RequiresCallback { get; set; }
        public Nullable<bool> HasUpdatedAddress { get; set; }
        public Nullable<bool> IsInFacility { get; set; }
        public Nullable<bool> ReceivesHospiceCare { get; set; }
        public Nullable<bool> ReceivesHomeCare { get; set; }
        public bool IsOrderConfirmed { get; set; }
        public string RelationShip { get; set; }
    }
}
