//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedSP
    {
        public int id { get; set; }
        public string TrackingNum { get; set; }
        public string Zip { get; set; }
        public string City_State { get; set; }
        public string Type { get; set; }
        public string Detail { get; set; }
        public string DDate { get; set; }
        public string var15 { get; set; }
        public string FN_LN { get; set; }
        public string var22 { get; set; }
        public string var23 { get; set; }
        public string var34 { get; set; }
        public string Street { get; set; }
        public Nullable<System.DateTime> uploadedDate { get; set; }
    }
}
