//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FedEx_POD_tbl
    {
        public System.Guid uID { get; set; }
        public Nullable<int> WorkOrder { get; set; }
        public string ConfirmationNum { get; set; }
        public string FedExReply { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> Account { get; set; }
        public string Status { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
    }
}
