//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FedEx_Tracking_Tbl
    {
        public int ID { get; set; }
        public Nullable<int> WorkOrder { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public string ConfirmationNum { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> IntWeight { get; set; }
        public string MeterNumber { get; set; }
        public string MedSurge { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
    }
}
