//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundReassessment
    {
        public int id { get; set; }
        public Nullable<int> Account { get; set; }
        public string FirstName { get; set; }
        public string PrimaryPhone { get; set; }
        public Nullable<bool> IsCorrectPerson { get; set; }
        public Nullable<bool> IsAuthorizedRep { get; set; }
        public string SpokeWith { get; set; }
        public string Relationship { get; set; }
        public Nullable<bool> HasPhoneChanged { get; set; }
        public Nullable<bool> HasAddressChanged { get; set; }
        public Nullable<bool> HasInsuranceChanged { get; set; }
        public string NewInsuranceProvider { get; set; }
        public string NewInsuranceProviderId { get; set; }
        public string NewInsuranceProviderPhone { get; set; }
        public string DoctorName { get; set; }
        public Nullable<bool> IsMeterWorking { get; set; }
        public Nullable<int> TestingTimes { get; set; }
        public Nullable<bool> IsInjectInsulin { get; set; }
        public string DayContType { get; set; }
        public string NiteContType { get; set; }
        public Nullable<bool> IsDayBowelIncontinent { get; set; }
        public Nullable<bool> IsNightBowelIncontinent { get; set; }
        public Nullable<bool> IsDayUrineIncontinent { get; set; }
        public Nullable<bool> IsNightUrineIncontinent { get; set; }
        public Nullable<bool> IsUsageEvening { get; set; }
        public Nullable<bool> IsMentallyImpaired { get; set; }
        public Nullable<bool> IsDiapering { get; set; }
        public Nullable<bool> HasSeizureDisorder { get; set; }
        public Nullable<bool> CanWalk { get; set; }
        public Nullable<bool> UseWalkAssist { get; set; }
        public Nullable<bool> HasAllergy { get; set; }
        public string AllergyMaterials { get; set; }
        public Nullable<bool> HasSoreOrRash { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<bool> EatByMouth { get; set; }
        public Nullable<bool> IsTubeFed { get; set; }
        public Nullable<bool> IsVerbal { get; set; }
        public Nullable<bool> HasProductOverstock { get; set; }
        public Nullable<bool> NeedAdditionSupplies { get; set; }
        public string AdditionalSupplies { get; set; }
        public Nullable<bool> UpdateStatus { get; set; }
        public Nullable<bool> Uploaded { get; set; }
        public Nullable<bool> IsReassessmentComplete { get; set; }
        public string PatientType { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public string InsulinType { get; set; }
        public string IncontinentType { get; set; }
    }
}
