//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundChangeAddress
    {
        public int id { get; set; }
        public int Account { get; set; }
        public string B_Address_1 { get; set; }
        public string B_Address_2 { get; set; }
        public string B_City { get; set; }
        public string B_State { get; set; }
        public string B_Zip { get; set; }
        public string S_Address_1 { get; set; }
        public string S_Address_2 { get; set; }
        public string S_City { get; set; }
        public string S_State { get; set; }
        public string S_Zip { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool UpdateStatus { get; set; }
        public Nullable<bool> Uploaded { get; set; }
    }
}
