//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundChangePhone
    {
        public int id { get; set; }
        public int Account { get; set; }
        public string PriPhone { get; set; }
        public string AltPhone { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool UpdateStatus { get; set; }
        public Nullable<bool> Uploaded { get; set; }
    }
}
