//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CallAgentDBEntitiesnew : DbContext
    {
        public CallAgentDBEntitiesnew()
            : base("name=CallAgentDBEntitiesnew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InboundProductConfirmation> InboundProductConfirmations { get; set; }
        public virtual DbSet<OrderConfirmation> OrderConfirmations { get; set; }
        public virtual DbSet<InboundChangeAddress> InboundChangeAddresses { get; set; }
        public virtual DbSet<DelOrderConfirmation> DelOrderConfirmations { get; set; }
        public virtual DbSet<InboundCall> InboundCalls { get; set; }
        public virtual DbSet<InboundChangePhone> InboundChangePhones { get; set; }
        public virtual DbSet<Call> Calls { get; set; }
        public virtual DbSet<ProductConfirmation> ProductConfirmations { get; set; }
        public virtual DbSet<PharmacyCall> PharmacyCalls { get; set; }
        public virtual DbSet<PharmacyConfirmation> PharmacyConfirmations { get; set; }
        public virtual DbSet<InboundReassmentProdConfirmation> InboundReassmentProdConfirmations { get; set; }
        public virtual DbSet<InboundReassessment> InboundReassessments { get; set; }
        public virtual DbSet<UpdatedMeridianCallsOB> UpdatedMeridianCallsOBs { get; set; }
        public virtual DbSet<InboundUpdateDoctor> InboundUpdateDoctors { get; set; }
        public virtual DbSet<InboundUpdateInsurance> InboundUpdateInsurances { get; set; }
        public virtual DbSet<tbl_AOB> tbl_AOB { get; set; }
    
        public virtual ObjectResult<sp_CustomerReordersupplies_MarkDone_Result> sp_CustomerReordersupplies_MarkDone()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CustomerReordersupplies_MarkDone_Result>("sp_CustomerReordersupplies_MarkDone");
        }
    }
}
