//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderConfirmation
    {
        public int Id { get; set; }
        public int AccountNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool IsOrderConfirmed { get; set; }
        public bool IsOrderReleasedFromHold { get; set; }
        public System.DateTime LoadedDate { get; set; }
        public string Source { get; set; }
    }
}
