//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmacyCall
    {
        public int Id { get; set; }
        public Nullable<int> CallId { get; set; }
        public int Account { get; set; }
        public System.DateTime RefillDate { get; set; }
        public bool Qty { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool UpdateStatus { get; set; }
        public bool ISConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public string SpokeWith { get; set; }
        public string RelationShip { get; set; }
    }
}
