//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RWOProdQtySubstitution_table
    {
        public int RowId { get; set; }
        public string oldProdCode { get; set; }
        public Nullable<int> oldQuantity { get; set; }
        public string newProdCode { get; set; }
        public Nullable<int> newQuantity { get; set; }
    }
}
