//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AOB
    {
        public int ID { get; set; }
        public Nullable<int> Account { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> isDocSubmitted { get; set; }
        public string DocSubmittedMethod { get; set; }
        public string ResendMethod { get; set; }
        public string ResendEmailAddress { get; set; }
        public string ResendFaxNumber { get; set; }
        public Nullable<bool> IsMailingCorrect { get; set; }
        public Nullable<bool> UseMailingAsPermBillingAddr { get; set; }
        public Nullable<int> MailingAddress_ID { get; set; }
        public Nullable<System.DateTime> CallTime { get; set; }
        public Nullable<System.DateTime> AOBSubmitDate { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
    }
}
