//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdatedMeridianCallsOB
    {
        public int Id { get; set; }
        public int CallId { get; set; }
        public System.DateTime Upload { get; set; }
        public bool Updated { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> ISConfirmed { get; set; }
    }
}
