//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_FutureOrderTypes2
    {
        public int Account { get; set; }
        public Nullable<System.DateTime> NextRepeatDate { get; set; }
        public string OrderType { get; set; }
    }
}
