//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCARRIER_USER_REGISTRATION
    {
        public int ID { get; set; }
        public int LOGIN_ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string PLANT_ID { get; set; }
        public string COMPANY_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string DESIGNATION { get; set; }
        public string DEPARTMENT { get; set; }
        public string ADDRESS_LINE1 { get; set; }
        public string ADDRESS_LINE2 { get; set; }
        public string ADDRESS_LINE3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<bool> ACTIVE_USER { get; set; }
        public string USER_ROLE { get; set; }
        public string Global { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_DATE_TIME { get; set; }
        public string PLANT_NAME { get; set; }
        public string PROFILE_IMAGE_URL { get; set; }
        public string BUILDING_NO { get; set; }
        public string MAIL_STOP { get; set; }
        public string COSTCENTER { get; set; }
        public string DG_SIGNATURE_ID { get; set; }
        public string COMPANY { get; set; }
        public string CONTACT { get; set; }
    }
}
