//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Areas.ColdFusionReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMN_Rules
    {
        public int cmrID { get; set; }
        public Nullable<System.DateTime> cmrCreated { get; set; }
        public string cmrCreatedBy { get; set; }
        public Nullable<System.DateTime> cmrDeleted { get; set; }
        public string cmrDeletedBy { get; set; }
        public Nullable<int> cmrReportType { get; set; }
        public Nullable<int> cmrPayerID { get; set; }
        public Nullable<int> cmrPayerTypeID { get; set; }
        public Nullable<int> cmrDocTypeID { get; set; }
        public Nullable<int> cmrProviderID { get; set; }
        public Nullable<int> cmrStatusCodeID { get; set; }
        public Nullable<int> cmrCategoryID { get; set; }
        public Nullable<byte> cmrInclude { get; set; }
        public Nullable<byte> cmrExclude { get; set; }
    }
}
