//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Areas.ColdFusionReports.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColdFusionIntranetEntities : DbContext
    {
        public ColdFusionIntranetEntities()
            : base("name=ColdFusionIntranetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FedEx_Password> FedEx_Password { get; set; }
        public virtual DbSet<Employees_AlphaSplit> Employees_AlphaSplit { get; set; }
        public virtual DbSet<CMN_Rules> CMN_Rules { get; set; }
    }
}
