//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Areas.ColdFusionReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FedEx_Password
    {
        public int pwdId { get; set; }
        public string logInId { get; set; }
        public string pwd { get; set; }
        public Nullable<System.DateTime> lastModDt { get; set; }
    }
}
