//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPS_Report.Areas.ColdFusionReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FedExMeterNumber
    {
        public int fmnID { get; set; }
        public string fmnMeter_Number { get; set; }
        public string fmnName { get; set; }
        public Nullable<System.DateTime> fmnUpdated { get; set; }
        public string fmnUpdatedBy { get; set; }
    }
}
