//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPSReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USPS_POD_tbl
    {
        public System.Guid uID { get; set; }
        public Nullable<int> WorkOrder { get; set; }
        public string ConfirmationNum { get; set; }
        public string USPSReply { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
